version: '3'
services:

  mongodb:
    build:
      context: .
      dockerfile: docker/mongodb/Dockerfile
    restart: always
    environment:
      DATABASE: logger_service
      USERNAME: admin
      PASSWORD: 000000
    ports:
      - '5100:27017'
    volumes:
      - ./data/db:/data/db

  api:
    build:
      context: .
      dockerfile: docker/jdk/Dockerfile
    restart: always
    ports:
      - '8100:8080'
    depends_on:
      - mongodb